### ISSUE TITLE
Unable to open project

### ISSUE THREAD

**Issue by SButterfly** [MatthewDiamond/MonoDevelop.ResxEditor#4]
I can't open project both on Windows and Mac. I see the error below
![default](https://cloud.githubusercontent.com/assets/4300612/7549854/8ed8ffd4-f65a-11e4-9d11-05283859fd61.png)

Can you help me to open the project?

**Comment by LightningDragon** [comment]
Do you have the AddinMaker installed in your Xamarin?

**Comment by MatthewDiamond** [comment]
"The project was made using the AddinMaker that the Xamarin developers provide. you will need to have it installed in order to open it" https://github.com/MatthewDiamond/MonoDevelop.ResxEditor/issues/1

**Comment by SButterfly** [comment]
@MatthewDiamond, I've already download it. Add have opened your project with it.
May be the problem is with gtk libraries?

Also I packed MonoDevelop.ResxEditor.dll ant then add pack to Xamarin Studio. 
![default](https://cloud.githubusercontent.com/assets/4300612/7553223/bedbd8b8-f6fb-11e4-8011-f9bccecc9ea1.png)

But I can't find out how to use it. Because there is no Resx editor on the context menu at .resx file.
![2](https://cloud.githubusercontent.com/assets/4300612/7553227/066f4d72-f6fc-11e4-8c7b-6785665eaca4.png)

**Comment by MatthewDiamond** [comment]
Why would it have to do with GTK? Is there a known bug with GTK? Either way I'm not seeing the AddinMaker in your screenshot are you certain you have it installed? As for it not appearing in the "Open With" menu I've only had that happen once, I disabled and re-enabled the add-in and it fixed the problem, give that a try.

**Comment by SButterfly** [comment]
Thanks, I reenabled addin and it appeared in the "Open With". As for GTK I wasn't quiet sure about it, it was just my suggestion.

After sitting for two hours I finally opened the project. I just created the new one and linked all files and references. And it works!! :) I will make a pull request in a nearest future.

**Comment by MatthewDiamond** [comment]
Thank you for contributing =)
