### ISSUE TITLE
Update for Xmarin Studio 6

### ISSUE THREAD

**Issue by gusmanb** [MatthewDiamond/MonoDevelop.ResxEditor#9]
I'm trying to install this on Xamarin Studio 6 and it's not compatible.

Are there any plans to update the plugin to support the new versions? This plugin has become part of my daily work flow and without it it's a pain to edit resx files...

**Comment by Macjon** [comment]
This is really easy, just download the source and update the addin maker nuget package. When you've done this, the addin is working perfectly.

**Comment by JannieT** [comment]
@Macjon, can you add a pull request?

**Comment by Macjon** [comment]
@JannieT done.

**Comment by Macjon** [comment]
@MatthewDiamond this issue can be closed. (2d86dfba2039ac6481863051b1891f82d9f82914)

**Comment by JannieT** [comment]
Cool! Thanks @Macjon
